import pandas as pd
from PFRHelper import PFRIDMatcher

years = range(2011, 2025)

for year in years:
    print(year)
    wr_and_te_df = pd.read_csv("wr_and_te_grades/pff_" + str(year) + "_wr_and_te.csv")
    wr_and_te_df = wr_and_te_df[~wr_and_te_df['PLAYER'].isna()]
    pfr_df = pd.read_csv("weekly_fantasy_points/" + str(year) + ".csv")
    database = [{'pfr_id': value} for value in pfr_df['PFR_Id'].unique()]

    matcher = PFRIDMatcher(database)

    wr_and_te_df['pfr_result'] = wr_and_te_df['PLAYER'].apply(matcher.get_pfr_id_with_info)
    wr_and_te_df['PFR_ID'] = wr_and_te_df['pfr_result'].apply(lambda x: x['pfr_id'])
    wr_and_te_df['match_status'] = wr_and_te_df['pfr_result'].apply(lambda x: x['status'])
    wr_and_te_df['match_count'] = wr_and_te_df['pfr_result'].apply(lambda x: x['match_count'])

    # Manual corrections for problematic players
    manual_corrections = [
        {'PLAYER': 'Steve Smith', 'TEAM': 'CAR', '#': '# 89', 'PFR_ID': 'SmitSt01'},
        {'PLAYER': 'Demaryius Thomas', 'TEAM': '*', '#': '*', 'PFR_ID': 'ThomDe03'},
        {'PLAYER': 'Kris Wilson', 'TEAM': '*', '#': '*', 'PFR_ID': 'WilsKr00'},
        {'PLAYER': 'Zach Miller', 'TEAM': 'JAX', '#': '# 86', 'PFR_ID': 'MillZa02'},
        {'PLAYER': 'James Jones', 'TEAM': '*', '#': '*', 'PFR_ID': 'JoneJa04'},
        {'PLAYER': 'Alex Smith', 'TEAM': '*', '#': '*', 'PFR_ID': 'SmitAl02'},
        {'PLAYER': 'Chad Johnson', 'TEAM': '*', '#': '*', 'PFR_ID': 'JohnCh01'},
        {'PLAYER': 'Mike Williams', 'TEAM': '*', '#': '# 19', 'PFR_ID': 'WillMi04'},
        {'PLAYER': 'Jacoby Jones', 'TEAM': '*', '#': '*', 'PFR_ID': 'JoneJa03'},
        {'PLAYER': 'Devin Thomas', 'TEAM': '*', '#': '*', 'PFR_ID': 'ThomDe02'},
        {'PLAYER': 'Donald Jones', 'TEAM': '*', '#': '*', 'PFR_ID': 'JoneDo00'},
        {'PLAYER': 'Mike Williams', 'TEAM': 'SEA', '#': '# 17', 'PFR_ID': 'WillMi03'},
        {'PLAYER': 'Michael Clayton', 'TEAM': '*', '#': '*', 'PFR_ID': 'ClayMi00'},
        {'PLAYER': 'Arnaz Battle', 'TEAM': '*', '#': '*', 'PFR_ID': 'BattAr00'},
        {'PLAYER': 'Steve Smith', 'TEAM': '*', '#': '# 11', 'PFR_ID': 'SmitSt02'},
        {'PLAYER': 'Steve Smith', 'TEAM': '*', '#': '# 12', 'PFR_ID': 'SmitSt02'},
        {'PLAYER': 'Kyle Adams', 'TEAM': '*', '#': '*', 'PFR_ID': 'AdamKy00'},
        {'PLAYER': 'Mike Sims-Walker', 'TEAM': '*', '#': '*', 'PFR_ID': 'WalkMi01'},
        {'PLAYER': 'Joe Hastings', 'TEAM': '*', '#': '*', 'PFR_ID': 'HastJo00'},
        {'PLAYER': 'Kerry Meier', 'TEAM': '*', '#': '*', 'PFR_ID': 'MeieKe00'},
        {'PLAYER': 'David Reed', 'TEAM': '*', '#': '*', 'PFR_ID': 'ReedDa00'},
        {'PLAYER': 'Jamar Newsome', 'TEAM': '*', '#': '*', 'PFR_ID': 'NewsJa00'},
        {'PLAYER': 'Tandon Doss', 'TEAM': '*', '#': '*', 'PFR_ID': 'DossTa00'},
        {'PLAYER': 'Delanie Walker', 'TEAM': '*', '#': '*', 'PFR_ID': 'WalkHu00'},
        {'PLAYER': 'Fendi Onobun', 'TEAM': '*', '#': '*', 'PFR_ID': 'OnobFe00'},
        {'PLAYER': 'Will Yeatman', 'TEAM': '*', '#': '*', 'PFR_ID': 'YeatWi00'},
        {'PLAYER': 'Collin Franklin', 'TEAM': '*', '#': '*', 'PFR_ID': 'FranCo00'},
        {'PLAYER': 'Richard Goodman', 'TEAM': '*', '#': '*', 'PFR_ID': 'GoodRi00'},
        {'PLAYER': 'Zach Miller', 'TEAM': 'SEA', '#': '# 86', 'PFR_ID': 'MillZa01'},
        {'PLAYER': 'Anthony Gonzalez', 'TEAM': '*', '#': '*', 'PFR_ID': 'GonzAn00'},
        {'PLAYER': 'Martin Rucker', 'TEAM': '*', '#': '*', 'PFR_ID': 'RuckMa00'},
        {'PLAYER': 'Jerrel Jernigan', 'TEAM': '*', '#': '*', 'PFR_ID': 'JernJe00'},
        {'PLAYER': 'Jeff Maehl', 'TEAM': '*', '#': '*', 'PFR_ID': 'MaehJe00'},
        {'PLAYER': 'Dave Thomas', 'TEAM': 'NO', '#': '# 85', 'PFR_ID': 'ThomDa02'},
        {'PLAYER': 'Antonio Brown', 'TEAM': '*', '#': '*', 'PFR_ID': 'BrowAn04'},
        {'PLAYER': 'Joe Morgan', 'TEAM': '*', '#': '*', 'PFR_ID': 'MorgJo01'},
        {'PLAYER': 'Josh Morgan', 'TEAM': '*', '#': '*', 'PFR_ID': 'MorgJo00'},
        {'PLAYER': 'Deonte Thompson', 'TEAM': '*', '#': '*', 'PFR_ID': 'ThomDe04'},
        {'PLAYER': 'Jordan White', 'TEAM': '*', '#': '*', 'PFR_ID': 'WhitJo02'},
        {'PLAYER': 'Chad Hall', 'TEAM': '*', '#': '*', 'PFR_ID': 'HallCh00'},
        {'PLAYER': 'Marlon Moore', 'TEAM': '*', '#': '*', 'PFR_ID': 'MoorMa02'},
        {'PLAYER': 'Dominique Jones', 'TEAM': '*', '#': '*', 'PFR_ID': 'JoneDo01'},
        {'PLAYER': 'Kevin Cone', 'TEAM': '*', '#': '*', 'PFR_ID': 'ConeKe00'},
        {'PLAYER': 'Richard Brockel', 'TEAM': '*', '#': '*', 'PFR_ID': 'BrocRi00'},
        {'PLAYER': 'Marvin McNutt', 'TEAM': '*', '#': '*', 'PFR_ID': 'McNuMa00'},
        {'PLAYER': 'Travis Beckum', 'TEAM': '*', '#': '*', 'PFR_ID': 'BeckTr00'},
        {'PLAYER': 'A.J. Jenkins', 'TEAM': '*', '#': '*', 'PFR_ID': 'JenkA.00'},
        {'PLAYER': 'Mike Brown', 'TEAM': 'JAX', '#': '# 12', 'PFR_ID': 'BrowMi00'},
        {'PLAYER': 'Patrick Turner', 'TEAM': '*', '#': '*', 'PFR_ID': 'TurnPa00'},
        {'PLAYER': 'Billy Bajema', 'TEAM': '*', '#': '*', 'PFR_ID': 'BajeBi00'},
        {'PLAYER': 'Visanthe Shiancoe', 'TEAM': '*', '#': '*', 'PFR_ID': 'ShiaVi00'},
        {'PLAYER': 'Dedrick Epps', 'TEAM': '*', '#': '*', 'PFR_ID': 'EppsDe00'},
        {'PLAYER': 'David Johnson', 'TEAM': '*', '#': '*', 'PFR_ID': 'JohnDa05'},
        {'PLAYER': 'Teddy Williams', 'TEAM': '*', '#': '*', 'PFR_ID': 'WillTe00'},
        {'PLAYER': 'Terrance Williams', 'TEAM': '*', '#': '*', 'PFR_ID': 'WillTe01'},
        {'PLAYER': 'Greg Jenkins', 'TEAM': '*', '#': '*', 'PFR_ID': 'JenkGr00'},
        {'PLAYER': 'Brian Robiskie', 'TEAM': '*', '#': '*', 'PFR_ID': 'RobiBr00'},
        {'PLAYER': 'Matthew Slater', 'TEAM': '*', '#': '*', 'PFR_ID': 'SlatMa00'},
        {'PLAYER': 'Michael Campbell', 'TEAM': '*', '#': '*', 'PFR_ID': 'CampMi01'},
        {'PLAYER': 'Darius Johnson', 'TEAM': '*', '#': '*', 'PFR_ID': 'JohnDa06'},
        {'PLAYER': 'Ryan Spadola', 'TEAM': '*', '#': '*', 'PFR_ID': 'SpadRy00'},
        {'PLAYER': 'Chase Coffman', 'TEAM': '*', '#': '*', 'PFR_ID': 'CoffCh00'},
        {'PLAYER': 'Damaris Johnson', 'TEAM': '*', '#': '*', 'PFR_ID': 'JohnDa04'},
        {'PLAYER': 'Steve Maneri', 'TEAM': '*', '#': '*', 'PFR_ID': 'ManeSt00'},
        {'PLAYER': 'Stephen Williams', 'TEAM': '*', '#': '*', 'PFR_ID': 'WillSt01'},
        {'PLAYER': 'D.J. Williams Jr.', 'TEAM': '*', '#': '*', 'PFR_ID': 'WillD.00'},
        {'PLAYER': 'Julian Talley', 'TEAM': '*', '#': '*', 'PFR_ID': 'TallJu00'},
        {'PLAYER': 'Chris Matthews', 'TEAM': '*', '#': '*', 'PFR_ID': 'MattCh00'},
        {'PLAYER': 'Steve Johnson', 'TEAM': '*', '#': '*', 'PFR_ID': 'JohnSt00'},
        {'PLAYER': 'Damian Williams', 'TEAM': '*', '#': '*', 'PFR_ID': 'WillDa04'},
        {'PLAYER': 'Daniel Fells', 'TEAM': '*', '#': '*', 'PFR_ID': 'FellDa00'},
        {'PLAYER': 'Julius Thomas', 'TEAM': '*', '#': '*', 'PFR_ID': 'ThomJu00'},
        {'PLAYER': 'Jarius Wright', 'TEAM': '*', '#': '*', 'PFR_ID': 'WrigJa02'},
        {'PLAYER': 'Darren Fells', 'TEAM': '*', '#': '*', 'PFR_ID': 'FellDa01'},
        {'PLAYER': 'Allen Robinson II', 'TEAM': '*', '#': '*', 'PFR_ID': 'RobiAl02'},
        {'PLAYER': 'Corey Brown', 'TEAM': '*', '#': '*', 'PFR_ID': 'BrowPh00'},
        {'PLAYER': 'Charles Johnson', 'TEAM': 'MIN', '#': '# 12', 'PFR_ID': 'JohnCh08'},
        {'PLAYER': 'Derek Carrier', 'TEAM': '*', '#': '*', 'PFR_ID': 'CarrDe00'},
        {'PLAYER': 'Freddie Martino', 'TEAM': '*', '#': '*', 'PFR_ID': 'MartFr00'},
        {'PLAYER': 'James Wright', 'TEAM': '*', '#': '*', 'PFR_ID': 'WrigJa03'},
        {'PLAYER': 'DeAndre Presley', 'TEAM': '*', '#': '*', 'PFR_ID': 'PresDe00'},
        {'PLAYER': 'Rodney Smith', 'TEAM': '*', '#': '*', 'PFR_ID': 'SmitRo05'},
        {'PLAYER': 'Tommy Streeter', 'TEAM': '*', '#': '*', 'PFR_ID': 'StreTo00'},
        {'PLAYER': 'Kassim Osgood', 'TEAM': '*', '#': '*', 'PFR_ID': 'OsgoKa00'},
        {'PLAYER': 'Aldrick Robinson', 'TEAM': '*', '#': '*', 'PFR_ID': 'RobiAl00'},
        {'PLAYER': 'Cobi Hamilton', 'TEAM': '*', '#': '*', 'PFR_ID': 'HamiCo00'},
        {'PLAYER': 'Richard Gordon', 'TEAM': '*', '#': '*', 'PFR_ID': 'GordRi00'},
        {'PLAYER': 'Brian Leonhardt', 'TEAM': '*', '#': '*', 'PFR_ID': 'LeonBr01'},
        {'PLAYER': 'Isaiah Burse', 'TEAM': '*', '#': '*', 'PFR_ID': 'BursIs01'},
        {'PLAYER': 'Mickey Shuler', 'TEAM': '*', '#': '*', 'PFR_ID': 'ShulMi01'},
        {'PLAYER': 'Kellen Davis', 'TEAM': '*', '#': '*', 'PFR_ID': 'DaviKe01'},
        {'PLAYER': 'Jordan Thompson', 'TEAM': '*', '#': '*', 'PFR_ID': 'ThomJo03'},
        {'PLAYER': 'Asante Cleveland', 'TEAM': '*', '#': '*', 'PFR_ID': 'ClevAs00'},
        {'PLAYER': 'Marvin Jones Jr.', 'TEAM': '*', '#': '*', 'PFR_ID': 'JoneMa02'},
        {'PLAYER': 'Marc Mariani', 'TEAM': '*', '#': '*', 'PFR_ID': 'MariMa00'},
        {'PLAYER': "James O'Shaughnessy", 'TEAM': '*', '#': '*', 'PFR_ID': "O'ShJa00"},
        {'PLAYER': "De'Anthony Thomas", 'TEAM': '*', '#': '*', 'PFR_ID': 'ThomDe05'},
        {'PLAYER': 'Josh Bellamy', 'TEAM': '*', '#': '*', 'PFR_ID': 'BellJo02'},
        {'PLAYER': 'Frankie Hammond', 'TEAM': '*', '#': '*', 'PFR_ID': 'HammFr00'},
        {'PLAYER': 'Vince Mayle', 'TEAM': '*', '#': '*', 'PFR_ID': 'MaylVi00'},
        {'PLAYER': 'Kevin Norwood', 'TEAM': '*', '#': '*', 'PFR_ID': 'NorwKe00'},
        {'PLAYER': 'Kasen Williams', 'TEAM': '*', '#': '*', 'PFR_ID': 'WillKa02'},
        {'PLAYER': 'Matt Hazel', 'TEAM': '*', '#': '*', 'PFR_ID': 'HazeMa01'},
        {'PLAYER': 'Rico Richardson', 'TEAM': '*', '#': '*', 'PFR_ID': 'RichRi00'},
        {'PLAYER': 'Marlon Brown', 'TEAM': '*', '#': '*', 'PFR_ID': 'BrowMa00'},
        {'PLAYER': 'Michael Thomas', 'TEAM': 'NO', '#': '# 13', 'PFR_ID': 'ThomMi05'},
        {'PLAYER': 'Daniel Braverman', 'TEAM': '*', '#': '*', 'PFR_ID': 'BravDa00'},
        {'PLAYER': 'Robbie Chosen', 'TEAM': '*', '#': '*', 'PFR_ID': 'AndeRo04'},
        {'PLAYER': 'Geremy Davis', 'TEAM': '*', '#': '*', 'PFR_ID': 'DaviGe00'},
        {'PLAYER': 'Kalif Raymond', 'TEAM': '*', '#': '*', 'PFR_ID': 'RaymKa00'},
        {'PLAYER': 'Mike Thomas', 'TEAM': 'LA', '#': '# 13', 'PFR_ID': 'ThomMi04'},
        {'PLAYER': 'Mike Thomas', 'TEAM': 'LA', '#': '# 88', 'PFR_ID': 'ThomMi04'},
        {'PLAYER': 'Mike Thomas', 'TEAM': 'CIN', '#': '# 80', 'PFR_ID': 'ThomMi04'},
        {'PLAYER': 'Khari Lee', 'TEAM': '*', '#': '*', 'PFR_ID': 'LeexKh00'},
        {'PLAYER': 'Braedon Bowman', 'TEAM': '*', '#': '*', 'PFR_ID': 'BowmBr00'},
        {'PLAYER': 'Hakeem Valles', 'TEAM': '*', '#': '*', 'PFR_ID': 'VallHa00'},
        {'PLAYER': 'Bobo Wilson', 'TEAM': '*', '#': '*', 'PFR_ID': 'WilsJe00'},
        {'PLAYER': 'Chris Thompson', 'TEAM': 'HST', '#': '# 14', 'PFR_ID': 'ThomCh05'},
        {'PLAYER': 'Maxx Williams', 'TEAM': '*', '#': '*', 'PFR_ID': 'WillMa04'},
        {'PLAYER': 'Isaac Whitney', 'TEAM': '*', '#': '*', 'PFR_ID': 'WhitIs00'},
        {'PLAYER': 'Ryan Malleck', 'TEAM': '*', '#': '*', 'PFR_ID': 'MallRy02'},
        {'PLAYER': 'John Ross', 'TEAM': '*', '#': '*', 'PFR_ID': 'RossJo00'},
        {'PLAYER': 'K.J. Brent', 'TEAM': '*', '#': '*', 'PFR_ID': 'BrenK.00'},
        {'PLAYER': 'Stacy Coley', 'TEAM': '*', '#': '*', 'PFR_ID': 'ColeSt00'},
        {'PLAYER': 'Marquis Bundy', 'TEAM': '*', '#': '*', 'PFR_ID': 'BundMa00'},
        {'PLAYER': 'Cody Core', 'TEAM': '*', '#': '*', 'PFR_ID': 'CoreCo00'},
        {'PLAYER': 'Matt LaCosse', 'TEAM': '*', '#': '*', 'PFR_ID': 'LaCoMa00'},
        {'PLAYER': 'Ed Eagan', 'TEAM': '*', '#': '*', 'PFR_ID': 'EagaEd00'},
        {'PLAYER': 'Logan Paulsen', 'TEAM': '*', '#': '*', 'PFR_ID': 'PaulLo00'},
        {'PLAYER': 'Cethan Carter', 'TEAM': '*', '#': '*', 'PFR_ID': 'CartCe00'},
        {'PLAYER': 'Gabe Holmes', 'TEAM': '*', '#': '*', 'PFR_ID': 'HolmGa00'},
        {'PLAYER': 'DJ Moore', 'TEAM': '*', '#': '*', 'PFR_ID': 'MoorD.00'},
        {'PLAYER': 'Garrett Griffin', 'TEAM': '*', '#': '*', 'PFR_ID': 'GrifGa00'},
        {'PLAYER': 'Justin Hardy', 'TEAM': '*', '#': '*', 'PFR_ID': 'HardJu00'},
        {'PLAYER': 'Pharoh Cooper', 'TEAM': '*', '#': '*', 'PFR_ID': 'CoopPh00'},
        {'PLAYER': 'Johnny Holton', 'TEAM': '*', '#': '*', 'PFR_ID': 'HoltJo00'},
        {'PLAYER': 'Isaiah Ford', 'TEAM': '*', '#': '*', 'PFR_ID': 'FordIs00'},
        {'PLAYER': 'Hunter Henry', 'TEAM': '*', '#': '*', 'PFR_ID': 'HenrHu00'},
        {'PLAYER': 'Mike Wallace', 'TEAM': '*', '#': '*', 'PFR_ID': 'WallMi00'},
        {'PLAYER': 'Chris Lacy', 'TEAM': '*', '#': '*', 'PFR_ID': 'LacyCh00'},
        {'PLAYER': 'Riley McCarron', 'TEAM': '*', '#': '*', 'PFR_ID': 'McCaRi00'},
        {'PLAYER': 'Jerome Cunningham', 'TEAM': '*', '#': '*', 'PFR_ID': 'CunnJe00'},
        {'PLAYER': 'Darrell Daniels', 'TEAM': '*', '#': '*', 'PFR_ID': 'DaniDa02'},
        {'PLAYER': 'Rashad Greene Sr.', 'TEAM': '*', '#': '*', 'PFR_ID': 'GreeRa00'},
        {'PLAYER': 'Cole Wick', 'TEAM': '*', '#': '*', 'PFR_ID': 'WickCo00'},
        {'PLAYER': 'Marquise Brown', 'TEAM': '*', '#': '*', 'PFR_ID': 'BrowMa04'},
        {'PLAYER': 'Corey Davis', 'TEAM': '*', '#': '*', 'PFR_ID': 'DaviCo03'},
        {'PLAYER': "D'haquille Williams", 'TEAM': 'BUF', '#': '# 82', 'PFR_ID': 'WillDu01'},
        {'PLAYER': 'Deonte Harty', 'TEAM': '*', '#': '*', 'PFR_ID': 'HarrDe07'},
        {'PLAYER': 'Ryan Griffin', 'TEAM': '*', '#': '*', 'PFR_ID': 'GrifRy00'},
        {'PLAYER': 'Josh Hill', 'TEAM': 'NO', '#': '# 89', 'PFR_ID': 'HillJo02'},
        {'PLAYER': 'Jace Sternberger', 'TEAM': '*', '#': '*', 'PFR_ID': 'SterJa00'},
        {'PLAYER': 'Chad Williams', 'TEAM': '*', '#': '*', 'PFR_ID': 'WillCh05'},
        {'PLAYER': 'KeeSean Johnson', 'TEAM': '*', '#': '*', 'PFR_ID': 'JohnKe07'},
        {'PLAYER': 'Jalen Guyton', 'TEAM': '*', '#': '*', 'PFR_ID': 'GuytJa01'},
        {'PLAYER': 'Taywan Taylor', 'TEAM': '*', '#': '*', 'PFR_ID': 'TaylTa00'},
        {'PLAYER': 'Damion Willis', 'TEAM': '*', '#': '*', 'PFR_ID': 'WillDa11'},
        {'PLAYER': "Lil'Jordan Humphrey", 'TEAM': '*', '#': '*', 'PFR_ID': 'HumpLi01'},
        {'PLAYER': 'Demetrius Harris', 'TEAM': '*', '#': '*', 'PFR_ID': 'HarrDe03'},
        {'PLAYER': 'Darrius Shepherd', 'TEAM': '*', '#': '*', 'PFR_ID': 'ShepDa00'},
        {'PLAYER': 'Travis Fulgham', 'TEAM': '*', '#': '*', 'PFR_ID': 'FulgTr00'},
        {'PLAYER': 'Tyron Johnson', 'TEAM': '*', '#': '*', 'PFR_ID': 'JohnTy03'},
        {'PLAYER': "De'Michael Harris", 'TEAM': '*', '#': '*', 'PFR_ID': 'HarrDe09'},
        {'PLAYER': 'Jordan Reed', 'TEAM': '*', '#': '*', 'PFR_ID': 'ReedJo02'},
        {'PLAYER': 'Colby Parkinson', 'TEAM': '*', '#': '*', 'PFR_ID': 'ParkCo02'},
        {'PLAYER': 'John Brown', 'TEAM': '*', '#': '*', 'PFR_ID': 'BrowJo02'},
        {'PLAYER': 'Tyler Johnson', 'TEAM': '*', '#': '*', 'PFR_ID': 'JohnTy00'},
        {'PLAYER': 'Hakeem Butler', 'TEAM': '*', '#': '*', 'PFR_ID': 'ButlHa00'},
        {'PLAYER': 'Rico Gafford', 'TEAM': '*', '#': '*', 'PFR_ID': 'GaffRi00'},
        {'PLAYER': 'Joe Reed', 'TEAM': '*', '#': '*', 'PFR_ID': 'ReedJo03'},
        {'PLAYER': 'Nate Becker', 'TEAM': '*', '#': '*', 'PFR_ID': 'BeckNa00'},
        {'PLAYER': 'Jeff Badet', 'TEAM': '*', '#': '*', 'PFR_ID': 'BadeJe00'},
        {'PLAYER': 'Antony Auclair', 'TEAM': '*', '#': '*', 'PFR_ID': 'AuclAn00'},
        {'PLAYER': 'Seth DeValve', 'TEAM': '*', '#': '*', 'PFR_ID': 'DevaSe00'},
        {'PLAYER': 'Eric Tomlinson', 'TEAM': '*', '#': '*', 'PFR_ID': 'TomlEr01'},
        {'PLAYER': 'Tajae Sharpe', 'TEAM': '*', '#': '*', 'PFR_ID': 'SharTa00'},
        {'PLAYER': 'Tyler Davis', 'TEAM': '*', '#': '*', 'PFR_ID': 'DaviTy02'},
        {'PLAYER': 'Cyril Grayson', 'TEAM': '*', '#': '*', 'PFR_ID': 'GrayCy01'},
        {'PLAYER': 'Mason Schreck', 'TEAM': '*', '#': '*', 'PFR_ID': 'SchrMa00'},
        {'PLAYER': 'Noah Togiai', 'TEAM': '*', '#': '*', 'PFR_ID': 'TogiNo00'},
        {'PLAYER': 'Ricky Seals-Jones', 'TEAM': '*', '#': '*', 'PFR_ID': 'SealRi00'},
        {'PLAYER': 'Kevin Rader', 'TEAM': '*', '#': '*', 'PFR_ID': 'RadeKe00'},
        {'PLAYER': 'DeSean Jackson', 'TEAM': '*', '#': '*', 'PFR_ID': 'JackDe00'},
        {'PLAYER': "Tre'Quan Smith", 'TEAM': '*', '#': '*', 'PFR_ID': 'SmitTr03'},
        {'PLAYER': 'Tyrell Williams', 'TEAM': '*', '#': '*', 'PFR_ID': 'WillTy00'},
        {'PLAYER': 'Isaiah Coulter', 'TEAM': '*', '#': '*', 'PFR_ID': 'CoulIs00'},
        {'PLAYER': 'Tyrie Cleveland', 'TEAM': '*', '#': '*', 'PFR_ID': 'ClevTy00'},
        {'PLAYER': 'Travis Benjamin', 'TEAM': '*', '#': '*', 'PFR_ID': 'BenjTr00'},
        {'PLAYER': 'David Moore', 'TEAM': '*', '#': '*', 'PFR_ID': 'MoorDa03'},
        {'PLAYER': 'Vyncint Smith', 'TEAM': '*', '#': '*', 'PFR_ID': 'SmitVy00'},
        {'PLAYER': 'Geronimo Allison', 'TEAM': '*', '#': '*', 'PFR_ID': 'AlliGe01'},
        {'PLAYER': 'Colin Thompson', 'TEAM': '*', '#': '*', 'PFR_ID': 'ThomCo03'},
        {'PLAYER': 'Stephen Sullivan', 'TEAM': '*', '#': '*', 'PFR_ID': 'SullSt00'},
        {'PLAYER': 'Rodney Adams', 'TEAM': '*', '#': '*', 'PFR_ID': 'AdamRo01'},
        {'PLAYER': 'Ben Ellefson', 'TEAM': '*', '#': '*', 'PFR_ID': 'ElleBe00'},
        {'PLAYER': 'Marcus Kemp', 'TEAM': '*', '#': '*', 'PFR_ID': 'KempMa00'},
        {'PLAYER': 'Jameson Williams', 'TEAM': '*', '#': '*', 'PFR_ID': 'WillJa11'},
        {'PLAYER': 'Hunter Long', 'TEAM': '*', '#': '*', 'PFR_ID': 'LongHu00'},
        {'PLAYER': 'Daniel Bellinger', 'TEAM': '*', '#': '*', 'PFR_ID': 'BellDa00'},
        {'PLAYER': 'Josh Ali', 'TEAM': '*', '#': '*', 'PFR_ID': 'AlixJo00'},
        {'PLAYER': 'Jake Tonges', 'TEAM': '*', '#': '*', 'PFR_ID': 'TongJa00'},
        {'PLAYER': 'Kirk Merritt', 'TEAM': '*', '#': '*', 'PFR_ID': 'MerrKi00'},
        {'PLAYER': 'James Washington', 'TEAM': '*', '#': '*', 'PFR_ID': 'WashJa00'},
        {'PLAYER': 'Josh Gordon', 'TEAM': '*', '#': '*', 'PFR_ID': 'GordJo02'},
        {'PLAYER': 'Tanner Gentry', 'TEAM': '*', '#': '*', 'PFR_ID': 'GentTa00'},
        {'PLAYER': 'David Bell', 'TEAM': '*', '#': '*', 'PFR_ID': 'BellDa02'},
        {'PLAYER': 'Stanley Morgan', 'TEAM': '*', '#': '*', 'PFR_ID': 'MorgSt02'},
        {'PLAYER': 'Lance McCutcheon', 'TEAM': '*', '#': '*', 'PFR_ID': 'McCuLa01'},
        {'PLAYER': 'Charlie Woerner', 'TEAM': '*', '#': '*', 'PFR_ID': 'WoerCh00'},
        {'PLAYER': 'Tanner Conner', 'TEAM': '*', '#': '*', 'PFR_ID': 'ConnTa00'},
        {'PLAYER': 'Tank Dell', 'TEAM': '*', '#': '*', 'PFR_ID': 'DellNa00'},
        {'PLAYER': 'Shedrick Jackson', 'TEAM': '*', '#': '*', 'PFR_ID': 'JackSh01'},
        {'PLAYER': 'Juwann Winfree', 'TEAM': '*', '#': '*', 'PFR_ID': 'WinfJu00'},
        {'PLAYER': 'Andy Isabella', 'TEAM': '*', '#': '*', 'PFR_ID': 'IsabAn00'},
        {'PLAYER': 'Anthony Firkser', 'TEAM': '*', '#': '*', 'PFR_ID': 'FirkAn00'},
        {'PLAYER': 'Trent Taylor', 'TEAM': '*', '#': '*', 'PFR_ID': 'TaylTr02'},
        {'PLAYER': 'Damiere Byrd', 'TEAM': '*', '#': '*', 'PFR_ID': 'ByrdDa00'},
        {'PLAYER': 'Jason Brownlee', 'TEAM': '*', '#': '*', 'PFR_ID': 'BrowJa07'},
        {'PLAYER': 'James Proche II', 'TEAM': '*', '#': '*', 'PFR_ID': 'ProcJa00'},
        {'PLAYER': 'Albert Okwuegbunam', 'TEAM': '*', '#': '*', 'PFR_ID': 'OkwuAl00'},
        {'PLAYER': 'Phillip Dorsett', 'TEAM': '*', '#': '*', 'PFR_ID': 'DorsPh00'},
        {'PLAYER': 'Julian Hill', 'TEAM': '*', '#': '*', 'PFR_ID': 'HillJu02'},
        {'PLAYER': 'Amari Rodgers', 'TEAM': '*', '#': '*', 'PFR_ID': 'RodgAm00'},
        {'PLAYER': 'Sean McKeon', 'TEAM': '*', '#': '*', 'PFR_ID': 'McKeSe01'},
        {'PLAYER': 'Gunner Olszewski', 'TEAM': '*', '#': '*', 'PFR_ID': 'OlszGu00'},
        {'PLAYER': 'Rodney Williams', 'TEAM': '*', '#': '*', 'PFR_ID': 'WillRo08'},
        {'PLAYER': 'Dareke Young', 'TEAM': '*', '#': '*', 'PFR_ID': 'YounDa02'},
        {'PLAYER': 'Steven Sims', 'TEAM': '*', '#': '*', 'PFR_ID': 'SimsSt00'},
        {'PLAYER': 'Tom Kennedy', 'TEAM': '*', '#': '*', 'PFR_ID': 'KennTo01'},
        {'PLAYER': "Ja'Tavion Sanders", 'TEAM': '*', '#': '*', 'PFR_ID': 'SandJa01'},
        {'PLAYER': 'Erik Ezukanma', 'TEAM': '*', '#': '*', 'PFR_ID': 'EzukEr00'},
        {'PLAYER': 'Charlie Jones', 'TEAM': '*', '#': '*', 'PFR_ID': 'JoneCh11'},
        {'PLAYER': 'Justyn Ross', 'TEAM': '*', '#': '*', 'PFR_ID': 'RossJu00'},
        {'PLAYER': 'Xavier Weaver', 'TEAM': '*', '#': '*', 'PFR_ID': 'WeavXa00'},
        {'PLAYER': 'John Samuel Shenker', 'TEAM': '*', '#': '*', 'PFR_ID': 'ShenJo00'},
        {'PLAYER': 'Brenden Bates', 'TEAM': '*', '#': '*', 'PFR_ID': 'BateBr00'},
        {'PLAYER': 'Jared Wayne', 'TEAM': '*', '#': '*', 'PFR_ID': 'WaynJa01'},
        {'PLAYER': 'Braxton Berrios', 'TEAM': '*', '#': '*', 'PFR_ID': 'BerrBr00'},
        {'PLAYER': 'Irv Smith Jr.', 'TEAM': '*', '#': '*', 'PFR_ID': 'SmitIr01'},
        {'PLAYER': 'Skyy Moore', 'TEAM': '*', '#': '*', 'PFR_ID': 'MoorSk01'},
        {'PLAYER': 'Brayden Willis', 'TEAM': '*', '#': '*', 'PFR_ID': 'WillBr06'},
        {'PLAYER': 'Baylor Cupp', 'TEAM': '*', '#': '*', 'PFR_ID': 'CuppBa00'},
        {'PLAYER': 'Devin Smith', 'TEAM': '*', '#': '*', 'PFR_ID': 'SmitDe04'}
    ]

    # Apply manual corrections
    for correction in manual_corrections:
        mask = wr_and_te_df['PLAYER'] == correction['PLAYER']
        if correction['TEAM'] != '*':
            mask &= wr_and_te_df['TEAM'] == correction['TEAM']
        if correction['#'] != '*':
            mask &= wr_and_te_df['#'] == correction['#']

        if mask.any():
            wr_and_te_df.loc[mask, 'PFR_ID'] = correction['PFR_ID']
            wr_and_te_df.loc[mask, 'match_status'] = 'manual_correction'

    problematic = wr_and_te_df[~wr_and_te_df['match_status'].isin(['unique', 'manual_correction'])]
    if len(problematic) > 0:
        print(problematic[['PLAYER', 'TEAM', '#', 'match_status', 'match_count']])

    duplicates_df = wr_and_te_df[wr_and_te_df['PFR_ID'].duplicated(keep=False)]
    if len(duplicates_df) > 0:
        print(duplicates_df[['PLAYER', 'TEAM', '#', 'PFR_ID']])

    wr_and_te_df = wr_and_te_df[wr_and_te_df['match_status'].isin(['unique', 'manual_correction'])]

    wr_and_te_df = wr_and_te_df.drop(['pfr_result', 'match_status', 'match_count', 'RANK', '#'], axis=1)

    wr_and_te_df = wr_and_te_df.drop(['PLAYER', 'POS', 'TEAM'], axis=1)

    to_numeric_cols = ['YDS', 'DROP', 'FUM', 'PBLK', 'YAC']
    wr_and_te_df[to_numeric_cols] = wr_and_te_df[to_numeric_cols].replace(',', '', regex=True).replace(
        '-', '', regex=True).apply(pd.to_numeric)

    wr_and_te_df.to_csv('new_wr_and_te_grades/cleaned_' + str(year) + '_wr_and_tes.csv', index=False)